//! Iter-299 (UM-3 leg 3): cross-polity cultural diffusion via trade.
//!
//! The substrate's diffusion law: culture spreads along interaction networks
//! with attenuation — trading partners exchange cultural items alongside
//! goods. i296–298 gave each polity its own holon and territory-routed
//! genesis, so polities now CARRY different memes; this pass is the channel
//! that lets them LEAK across the boundary:
//!
//! A `TradeOccurred` (or Trade `InteractionOccurred`) between agents of two
//! DIFFERENT polities exposes the receiver's polity to the sender's
//! polity-namespaced genesis memes at a damped transmission rate. Damping
//! (`TRADE_DIFFUSION_DAMP`) reflects the substrate principle that trade is a
//! weaker cultural channel than gossip (§13.1 weights trade interactions at
//! 0.3 vs gossip's full weight).
//!
//! Zero-at-zero: no polities assigned, or no cross-polity trades in the
//! window → the pass is a no-op (legacy single-village runs untouched).
//! Deterministic: event-order scan, no RNG (transmission is deterministic —
//! the trade ITSELF is the sampler; damped host_count growth approximates
//! per-agent exposure without consuming draws from any RNG stream).

use mindstrata_core::clock::Tick;
use mindstrata_core::event::SimEvent;
use mindstrata_social::culture::MemeRegistry;

/// Trade-diffusion damping: cross-polity trades carry only this fraction of
/// the per-trade meme exposure that gossip carries (the §13.1 trade weight).
pub const TRADE_DIFFUSION_DAMP: f64 = 0.3;

/// Genesis-tag prefix — memes carrying it inside their description were
/// GENERATED by the Era IV genesis pass; only generated culture diffuses
/// (founding memories are the polity's export good; seeded stock is
/// universal and needs no diffusion channel).
const GENESIS_TAG: &str = "[genesis:";

/// One cross-polity trade diffusion step over the tick's event window.
///
/// `polity_members[p]` is the sorted member-agent list of polity `p`
/// (i296 contract). For each trade event whose participants belong to
/// different polities, the RECEIVER's polity imports the SENDER's
/// namespaced genesis memes: `host_count` grows by the damped weight
/// (accumulated in f64 against the Fixed-4 truncation hazard, then
/// quantized once), bounded by the polity's member count. Import order is
/// event order; no RNG.
pub fn system_trade_diffusion(
    events: &[SimEvent],
    tick: Tick,
    polity_members: &[Vec<usize>],
    registry: &mut MemeRegistry,
) {
    if polity_members.len() < 2 {
        return;
    }
    // Agent → polity lookup (linear scan per participant; populations are
    // small and the window only contains cross-polity trades).
    let polity_of = |agent: usize| -> Option<usize> {
        polity_members
            .iter()
            .position(|members| members.contains(&agent))
    };

    for ev in events {
        let (from, to) = match ev {
            SimEvent::TradeOccurred { buyer, seller, .. } => {
                (buyer.as_u64() as usize, seller.as_u64() as usize)
            }
            SimEvent::InteractionOccurred {
                from,
                to,
                kind: mindstrata_core::event::InteractionKind::Trade,
                ..
            } => (from.as_u64() as usize, to.as_u64() as usize),
            _ => continue,
        };
        let (Some(pf), Some(pt)) = (polity_of(from), polity_of(to)) else {
            continue;
        };
        if pf == pt {
            continue; // intra-polity trade: no cross-boundary diffusion
        }
        // The RECEIVER's polity imports the SENDER's generated memes. Both
        // directions occur naturally across the event stream (each trade
        // diffuses one way); the registry is shared, so a p0-origin meme
        // never double-registers in p1's namespace — host_count growth is
        // the diffusion signal for EXISTING foreign memes, registration for
        // NEW ones.
        let (src, dst) = (pf, pt);
        let pop = polity_members[dst].len() as u32;
        let damped = (TRADE_DIFFUSION_DAMP * 100.0).round(); // raw Fixed-4 units per trade
        for meme in &mut registry.memes {
            if !meme.active || !meme.description.contains(GENESIS_TAG) {
                continue;
            }
            // Only memes of the SENDER's namespace diffuse INTO the
            // receiver's polity.
            let ns = format!("[genesis:p{src}:");
            if !meme.description.contains(&ns) {
                continue;
            }
            // Damped host-count growth, capped at the receiving polity's
            // population. Fixed-4 cannot hold sub-0.01 increments, so the
            // f64 accumulation happens via saturating adds of quantized
            // damped units (one trade per event, deterministic).
            meme.host_count = (meme.host_count.saturating_add(damped as u32)).min(pop);
            // The trade counterparty receives the sender's culture.
            meme.add_host(to);
            let _ = tick;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use mindstrata_core::clock::Tick;
    use mindstrata_core::event::SimEvent;
    use mindstrata_core::fixed::Fixed;
    use mindstrata_core::id::AgentId;
    use mindstrata_social::culture::{Meme, MemeContent};

    fn genesis_meme(tag_ns: &str) -> Meme {
        Meme::new(
            0,
            format!("The East Well is what our people kept {tag_ns}"),
            MemeContent::Historical,
            Fixed::from_f64(0.6),
            Fixed::from_f64(0.9),
            0,
            Fixed::from_f64(0.8),
            Fixed::from_f64(0.03),
        )
    }

    fn trade_event(a: u64, b: u64, tick: Tick) -> SimEvent {
        SimEvent::TradeOccurred {
            buyer: AgentId::new(a),
            seller: AgentId::new(b),
            good: mindstrata_core::id::ResourceId::new(0),
            quantity: Fixed::from_f64(1.0),
            price: Fixed::from_f64(1.0),
            tick,
        }
    }

    #[test]
    fn cross_polity_trade_diffuses_sender_memes() {
        let tick = Tick::new(10);
        let mut registry = MemeRegistry::default();
        registry.register(genesis_meme("[genesis:p0:Identity:Historical:2]"));
        let hosts_before = registry.memes[0].host_count;

        // p0 = {0,1}, p1 = {2,3}: a 0→2 trade is cross-polity.
        let evs = vec![trade_event(0, 2, tick)];
        system_trade_diffusion(&evs, tick, &[vec![0, 1], vec![2, 3]], &mut registry);

        assert!(
            registry.memes[0].host_count > hosts_before,
            "cross-polity trade must diffuse the sender's meme ({} → {})",
            hosts_before,
            registry.memes[0].host_count
        );
    }

    #[test]
    fn intra_polity_trade_diffuses_nothing() {
        let tick = Tick::new(10);
        let mut registry = MemeRegistry::default();
        registry.register(genesis_meme("[genesis:p0:Identity:Historical:2]"));
        let before = registry.memes[0].host_count;

        let evs = vec![trade_event(0, 1, tick)]; // both in p0
        system_trade_diffusion(&evs, tick, &[vec![0, 1], vec![2, 3]], &mut registry);
        assert_eq!(
            registry.memes[0].host_count, before,
            "intra-polity trade must not diffuse across the boundary"
        );
    }

    #[test]
    fn diffusion_is_inert_without_polities() {
        let tick = Tick::new(10);
        let mut registry = MemeRegistry::default();
        registry.register(genesis_meme("[genesis:p0:Identity:Historical:2]"));
        let evs = vec![trade_event(0, 1, tick)];
        system_trade_diffusion(&evs, tick, &[], &mut registry);
        assert!(
            registry.memes[0].host_count == 0,
            "no polities → the legacy single-village no-op contract"
        );
    }

    #[test]
    fn trade_records_the_receiver_in_hosting_set() {
        let tick = Tick::new(10);
        let mut registry = MemeRegistry::default();
        registry.register(genesis_meme("[genesis:p0:Identity:Historical:2]"));
        // Repeated cross trades to the SAME receiver must be idempotent.
        let evs = vec![
            trade_event(0, 2, tick),
            trade_event(1, 2, tick),
            trade_event(0, 3, tick),
        ];
        system_trade_diffusion(&evs, tick, &[vec![0, 1], vec![2, 3]], &mut registry);
        let meme = &registry.memes[0];
        assert!(
            meme.is_hosted_by(2) && meme.is_hosted_by(3),
            "the trade receiver must appear in the hosting set"
        );
        assert_eq!(
            meme.hosts.len(),
            2,
            "re-transmission to the same receiver must not double-host: {:?}",
            meme.hosts
        );
    }

    #[test]
    fn foreign_namespace_must_not_grow_from_own_trade() {
        let tick = Tick::new(10);
        let mut registry = MemeRegistry::default();
        // A p1-namespace meme: a p0-member trading outward must not inflate it.
        registry.register(genesis_meme("[genesis:p1:Identity:Historical:2]"));
        let before = registry.memes[0].host_count;
        let evs = vec![trade_event(0, 2, tick)]; // 0∈p0 sends, 2∈p1 receives
        system_trade_diffusion(&evs, tick, &[vec![0, 1], vec![2, 3]], &mut registry);
        // The p1 meme belongs to the RECEIVER — a p0→p1 trade diffuses p0's
        // memes into p1, not p1's own memes. host_count must stay.
        assert_eq!(
            registry.memes[0].host_count, before,
            "a trade must not diffuse the receiver's own memes"
        );
    }
}
