[package]
name = "mindstrata-psych"
version.workspace = true
edition.workspace = true

[dependencies]
mindstrata-core = { workspace = true }
mindstrata-person = { workspace = true }
mindstrata-development = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rand_chacha = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
