#!/usr/bin/env python3
"""afa_codegen.py — emit deterministic Rust canon tables from vendor/afa CSVs.

Usage: python3 scripts/afa_codegen.py [vendor-dir default: vendor/afa]

Outputs (inside the vendor dir):
  gen/canon_tables.rs   — ladder/line/coupling tables as const arrays
  COVERAGE.md           — mapping report: every curated line×stage covered,
                          absent, or partial, per vault depth_status

Determinism: fixed row order (CSV order = vault directory order), no
timestamps, no environment reads. Two consecutive runs are byte-identical.
"""

from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def rs_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_ladder(rows: list[dict]) -> list[str]:
    out = ["/// Canonical 17-stage unified ladder (vendored from KosmOS stages.md).",
           "pub static LADDER: &[LadderStage] = &["]
    for r in rows:
        out.append(
            "    LadderStage {{ stage: {}, slug: {}, name: {}, altitude: {}, "
            "identity_band: {}, mhc_order: {}, mhc_name: {}, kegan: {} }},".format(
                r["stage"], rs_str(r["slug"]), rs_str(r["canonical_name"]),
                rs_str(r["altitude"]), rs_str(r["identity_band"]),
                rs_str(r["mhc_order"]), rs_str(r["mhc_name"]), rs_str(r["kegan"]),
            )
        )
    out.append("];")
    return out


def emit_lines(rows: list[dict]) -> list[str]:
    out = ["/// Line registries present in the vault (superset of the AP3 curated set).",
           "pub static LINES: &[LineEntry] = &["]
    for r in rows:
        cells_req = r["matrix_cells_required"].strip() or "0"
        if not cells_req.isdigit():
            cells_req = "0"
        out.append(
            "    LineEntry {{ slug: {}, kind: {}, quadrant: {}, status: {}, "
            "matrix_cells_required: {}, matrix_depth: {} }},".format(
                rs_str(r["line_slug"]), rs_str(r["kind"]), rs_str(r["quadrant"]),
                rs_str(r["status"]), cells_req,
                rs_str(r["matrix_depth"]),
            )
        )
    out.append("];")
    return out


def emit_couplings(rows: list[dict]) -> list[str]:
    out = ["/// Observed line×stage cells (depth_status per vault frontmatter).",
           "pub static COUPLINGS: &[Coupling] = &["]
    for r in rows:
        out.append(
            "    Coupling {{ line: {}, stage: {}, stage_slug: {}, altitude: {}, "
            "depth_status: {} }},".format(
                rs_str(r["line"]), int(r["stage"]), rs_str(r["stage_slug"]),
                rs_str(r["altitude"]), rs_str(r["depth_status"]),
            )
        )
    out.append("];")
    return out


def coverage(lines: list[dict], couplings: list[dict]) -> list[str]:
    by_line: dict[str, set[int]] = defaultdict(set)
    depth: dict[tuple[str, int], str] = {}
    for c in couplings:
        try:
            stage = int(c["stage"])
        except ValueError:
            continue
        by_line[c["line"]].add(stage)
        depth[(c["line"], stage)] = c["depth_status"]
    out = [
        "# Codegen Coverage",
        "",
        "Vault cell inventory vs the canonical 17-stage ladder.",
        "States: `complete` cells counted per depth_status; missing stages listed explicitly.",
        "",
        "| line | cells | complete | draft/partial | missing stages |",
        "|---|---|---|---|---|",
    ]
    for l in lines:
        slug = l["line_slug"]
        have = by_line.get(slug, set())
        complete = sum(1 for s in have if depth.get((slug, s)) == "complete")
        other = len(have) - complete
        missing = sorted(set(range(1, 18)) - have)
        missing_s = ", ".join(map(str, missing)) if missing else "—"
        out.append(f"| {slug} | {len(have)}/17 | {complete} | {other} | {missing_s} |")
    out.append("")
    out.append(f"lines={len(lines)} coupling_cells={len(couplings)}")
    return out


def main(argv: list[str]) -> int:
    vend = Path(argv[1]).resolve() if len(argv) > 1 else Path("vendor/afa").resolve()
    ladder = read_csv(vend / "ladder.csv")
    lines = read_csv(vend / "lines.csv")
    couplings = read_csv(vend / "couplings.csv")

    gen = vend / "gen"
    gen.mkdir(exist_ok=True)
    # Data-only emission: types are declared (with docs) by the consuming crate
    # (crates/mindstrata-development/src/canon_gen.rs) which include!s this file.
    header = (
        "// GENERATED by scripts/afa_codegen.py from vendor/afa CSVs — do not edit.\n"
        "// Deterministic: rerun produces byte-identical output.\n"
        "// Types LadderStage/LineEntry/Coupling are declared by the including module.\n\n"
    )
    body = "\n".join(
        emit_ladder(ladder) + [""] + emit_lines(lines) + [""] + emit_couplings(couplings)
    )
    (gen / "canon_tables.rs").write_text(header + body + "\n", encoding="utf-8")
    (vend / "COVERAGE.md").write_text("\n".join(coverage(lines, couplings)) + "\n", encoding="utf-8")
    print(f"ladder={len(ladder)} lines={len(lines)} couplings={len(couplings)} -> gen/canon_tables.rs")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
