#!/usr/bin/env python3
"""Regenerate docs/scaling/coupling_map.md from live source.

v2 reality: the shim design means sources reach domains via `crate::<module>`
(legacy paths through sim/lib.rs re-exports), so raw `mindstrata_x::` counts
are ~zero. True coupling therefore has two layers:

  1. Enforced DAG  — declared dependencies in crates/*/Cargo.toml.
  2. Orchestration heat — how often sim sources touch each legacy module,
     annotated with the crate that owns it today.

Re-run after structural moves; generated, never hand-edited."""
import collections
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---- layer 1: enforced DAG from Cargo.tomls -------------------------------
dep = {}
for toml in glob.glob(os.path.join(ROOT, "crates", "*", "Cargo.toml")):
    m = re.search(r"crates[/\\](mindstrata-[a-z]+)", toml)
    if m is None:
        continue
    name = m.group(1)
    text = open(toml, encoding="utf-8").read()
    dep[name] = sorted(set(re.findall(r"^(mindstrata-[a-z]+)", text, re.M)) - {name})

# ---- layer 2: module ownership + orchestration heat -----------------------
owner = {}          # legacy module -> owning crate
for src in glob.glob(os.path.join(ROOT, "crates", "mindstrata-sim", "src", "lib.rs")):
    text = open(src, encoding="utf-8").read()
    # pub mod X { pub use mindstrata_y:: ... }  |  plain pub mod X;
    for m in re.finditer(r"pub mod ([a-z_]+)\s*\{[^}]*?mindstrata_([a-z_]+)", text):
        owner[m.group(1)] = f"mindstrata_{m.group(2)}"

heat = collections.Counter()       # module -> refs inside sim sources
for src in glob.glob(os.path.join(ROOT, "crates", "mindstrata-sim", "src", "**", "*.rs"), recursive=True):
    if src.endswith("lib.rs"):
        continue
    text = open(src, encoding="utf-8").read()
    heat.update(re.findall(r"\bcrate::([a-z_]+)::", text))

lines = [
    "# Coupling Map v2 — post-crate-ladder",
    "",
    "Generated by `scripts/gen_coupling_map.py`; do not hand-edit.",
    "Pre-extraction v1 (module-level seam survey used to pick S2/S3 seams):",
    "`git show 54d7f1c:docs/scaling/coupling_map.md`.",
    "",
    "## Layer 1 — enforced DAG (Cargo-declared, compile-checked)",
    "",
]
for c in sorted(dep):
    lines.append(f"- **{c.removeprefix('mindstrata_')}** ← {', '.join(d.removeprefix('mindstrata_') for d in dep[c]) or '(leaf)'}")

lines += [
    "",
    "## Layer 2 — orchestration heat (sim sources → module → owning crate)",
    "",
    "| refs | module | owner |",
    "|-----:|--------|-------|",
]
for mod, n in heat.most_common():
    own = owner.get(mod, "mindstrata-sim (local)")
    lines.append(f"| {n} | {mod} | {own.removeprefix('mindstrata_')} |")

out = os.path.join(ROOT, "docs", "scaling", "coupling_map.md")
open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(f"wrote {out}: {len(dep)} crates, {len(heat)} modules tracked")
