[package]
name = "mindstrata-cli"
description = "CLI interface for running Mindstrata simulations"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mindstrata"
path = "src/main.rs"

[dependencies]
mindstrata-core = { workspace = true }
mindstrata-sim = { workspace = true }
mindstrata-tui = { path = "../mindstrata-tui" }
mindstrata-render = { path = "../mindstrata-render" }
image = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
